import React from 'react';
import {
  BookOutlined,
  CalendarOutlined,
  DollarOutlined,
  FileTextOutlined,
  FolderOpenOutlined,
  FormOutlined,
  LineChartOutlined,
  ScheduleOutlined,
  SettingOutlined,
  TeamOutlined,
  UsergroupAddOutlined,
} from "@ant-design/icons";

export const moduleIcons = {
  'Class Schedule': <CalendarOutlined style={{ color: '#C68A00' }} />,
  'Class Information': <BookOutlined style={{ color: '#C68A00' }} />,
  'Handling of Grades': <FormOutlined style={{ color: '#C68A00' }} />,
  'Viewing of OTE': <LineChartOutlined style={{ color: '#C68A00' }} />,
  'Teacher Documents': <FileTextOutlined style={{ color: '#C68A00' }} />,
  'Manage Applications': <UsergroupAddOutlined style={{ color: '#C68A00' }} />,
  'Manage Accounts': <TeamOutlined style={{ color: '#C68A00' }} />,
  'Manage Student Records': <FolderOpenOutlined style={{ color: '#C68A00' }} />,
  'Manage Enrollment': <FormOutlined style={{ color: '#C68A00' }} />,
  'Manage Schedule': <ScheduleOutlined style={{ color: '#C68A00' }} />,
  'Manage Program': <SettingOutlined style={{ color: '#C68A00' }} />,
  'Manage Payments': <DollarOutlined style={{ color: '#C68A00' }} />,
  'Manage Queue': <ScheduleOutlined style={{ color: '#C68A00' }} />,
  'Overall System Logs': <FileTextOutlined style={{ color: '#C68A00' }} />,
  'Create Announcements': <FileTextOutlined style={{ color: '#C68A00' }} />,
  'Student Handbook': <BookOutlined style={{ color: '#C68A00' }} />,
  'Certificate of Registration': <FileTextOutlined style={{ color: '#C68A00' }} />,
  'Flowchart': <FormOutlined style={{ color: '#C68A00' }} />,
  'Online Class Registration': <FormOutlined style={{ color: '#C68A00' }} />,
  'Viewing of Grades': <FormOutlined style={{ color: '#C68A00' }} />,
  'Online Teacher\'s Evaluation': <FormOutlined style={{ color: '#C68A00' }} />,
  'Student Ledger': <DollarOutlined style={{ color: '#C68A00' }} />,
  'Enrollment': <FormOutlined style={{ color: '#C68A00' }} />,
  'Joining Queue': <ScheduleOutlined style={{ color: '#C68A00' }} />,
  'Pay Bills': <DollarOutlined style={{ color: '#C68A00' }} />,
};
